use_default_settings: true

server:
  secret_key: "${SEARXNG_SECRET_KEY}"
  base_url: "https://search.van-vliet.eu/"
  bind_address: "0.0.0.0:8080"
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "nl"

ui:
  static_use_hash: true
  infinite_scroll: false
  default_theme: simple

outgoing:
  request_timeout: 10.0
  max_request_timeout: 30.0
  useragent_suffix: ""

engines:
  - name: google
    engine: google
    disabled: false
  - name: bing
    engine: bing
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    disabled: false
  - name: wikipedia
    engine: wikipedia
    language: nl
    disabled: false
